<?php

namespace WeDevBr\Bankly\Enums\Pix\ScheduledPix;

enum StatusEnum: string
{
    case AWAITING_ENRICHMENT = 'AWAITING_ENRICHMENT';
    case CANCELED = 'CANCELED';
    case SENT_PRE_VALIDATION = 'SENT_PRE_VALIDATION';
    case PROCESSING = 'PROCESSING';
    case RESCHEDULED = 'RESCHEDULED';
    case SCHEDULED = 'SCHEDULED';
    case ATTEMPTS_EXCEEDED = 'ATTEMPTS_EXCEEDED';
    case SUCCESSFULLY_COMPLETED = 'SUCCESSFULLY_COMPLETED';
    case UNSUCCESSFULLY_COMPLETED = 'UNSUCCESSFULLY_COMPLETED';
}
